import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Provider from "./provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex gap-5">
          <Link
            href="/"
            className=" text-blue-500 border border-blue-500 px-2 py-1 rounded-md"
          >
            HOME
          </Link>
          <Link
            href="/todos"
            className=" text-blue-500 border border-blue-500 px-2 py-1 rounded-md"
          >
            TODOS
          </Link>
        </nav>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
